args_unknown: '[]'
base_model_name: '"v_48_020"'
batch_size: '10000'
beta: '0.034260398613046285'
debug: None
device: '"cuda"'
domain: '"d"'
env: '"py"'
hyp: None
hyp_n: None
job: '"qf9xm"'
loch_path: None
lr: '2.8559193819177474e-06'
max_protein_length: '10000'
mhc_1_alleles: '"b69bb1"'
mhc_1_predictor: '"pwm_dynamic"'
multithreading: 'False'
num_epochs: '20'
num_examples_per_epoch: '1000000'
project_path: None
reload_data_every_n_epochs: '2'
rescut: '3.5'
save_model_every_n_epochs: '1'
task: '""'
temperature: '0.7586130416015283'
